In [ ]:
# In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate
# written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning
# model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,
# 2 yr experience, 9 test score, 6 interview score
# 12 yr experience, 10 test score, 10 interview score

In [19]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import word2number as w2n



In [17]:
hiring= pd.read_csv('hiring.csv', index_col= False)

In [7]:
# Converting experience column values into number 
#word2number


!pip install word2number


In [26]:
hiring['experience']

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [31]:
from word2number import w2n

# Example usage
word = "twenty"
num = w2n.word_to_num(word)
print(num)  # This should print: 20


20


In [34]:
hiring.experience= hiring.experience.apply(lambda x: w2n.word_to_num(x) if isinstance(x, str) else x)

In [37]:
hiring.experience.median()

6.0

In [40]:
hiring.experience= hiring.experience.fillna(hiring.experience.median())

In [43]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [48]:
hiring = hiring.rename(columns={'test_score(out of 10)': 'test_score'})
hiring = hiring.rename(columns={'interview_score(out of 10)': 'interview_score'})
hiring = hiring.rename(columns={'salary($)': 'salary'})

In [51]:
hiring

experience  test_score  interview_score  salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [53]:
hiring.test_score= hiring.test_score.fillna(hiring.test_score.median())

In [55]:
hiring

experience  test_score  interview_score  salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [62]:
# Creating object
reg= linear_model.LinearRegression()

In [66]:
reg.fit(hiring[['experience', 'test_score', 'interview_score']], hiring.salary)

LinearRegression()

In [70]:
# 2 yr experience, 9 test score, 6 interview score
reg.predict([[2,9,6]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47056.91056911])

In [72]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [76]:
reg.intercept_

11869.918699186943

In [78]:

# Answers match
2813.00813008*2 + 1333.33333333*9 + 2926.8292682* 6 + 11869.918699186943

47056.91056851694

In [80]:
# 12 yr experience, 10 test score, 10 interview score
reg.predict([[12, 10, 10]])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88227.64227642])

In [82]:
# Answers match
2813.00813008*12 + 1333.33333333*10 + 2926.8292682* 10 + 11869.918699186943

88227.64227544694